// Generated by CoffeeScript 1.7.1
(function() {
  jQuery.sap.require("com.mitsuruog.sapui5.showroom.controls.SayHello");

  jQuery.sap.require("com.mitsuruog.sapui5.showroom.controls.Card");

  jQuery.sap.require("com.mitsuruog.sapui5.showroom.controls.BlueContainer");

  jQuery.sap.require("com.mitsuruog.sapui5.showroom.controls.HoverButton");

  sap.ui.jsview("com.mitsuruog.sapui5.showroom.view.Controls", {
    getControllerName: function() {
      return "com.mitsuruog.sapui5.showroom.view.Controls";
    },
    createContent: function(oController) {
      var blueContainer, panel1, panel2, pinkCard;
      this.page = new sap.m.Page({
        title: "Creating custom controls"
      }, panel1 = new sap.m.Panel({
        headerText: "Hello world.",
        content: [
          new mitsuruog.SayHello, new mitsuruog.SayHello({
            name: "mitsuruog"
          }), new mitsuruog.SayHello({
            name: "{/name}"
          })
        ]
      }), pinkCard = new mitsuruog.Card({
        name: "pink mitsuruog"
      }), pinkCard.addStyleClass("pink"), panel2 = new sap.m.Panel({
        headerText: "My business card",
        content: [
          new mitsuruog.Card({
            name: "mitsuruog",
            size: "100px"
          }), pinkCard
        ]
      }), blueContainer = new mitsuruog.BlueContainer);
      this.page.addContent(panel1);
      this.page.addContent(panel2);
      this.page.addContent(blueContainer);
      return this.page;
    }
  });

}).call(this);
